package ma.whitecare.entities.enums;

public enum CategorieStatistique {
    CONSULTATIONS,

    // Statistiques Patients
    PATIENTS_NOUVEAUX,
    PATIENTS_ACTIFS,
    PATIENTS_FIDELES,
    REPARTITION_AGE,
    REPARTITION_GENRE,
    REPARTITION_ASSURANCE,

    // Statistiques Médicales
    CONSULTATIONS_TOTALES,
    CONSULTATIONS_PAR_MEDECIN,
    TYPES_CONSULTATION,
    ACTES_REALISES,
    INTERVENTIONS_DENTAIRES,
    URGENCES_TRAITEES,

    // Statistiques Financières
    CHIFFRE_AFFAIRE,
    REVENUS_MENSUELS,
    FACTURES_IMPAYEES,
    TAUX_ENCAISSEMENT,
    REPARTITION_REVENUS,
    DEPENSES_CABINET,

    // Statistiques RDV
    RDV_PLANIFIES,
    RDV_ANNULEES,
    TAUX_PRESENTATION,
    RETARDS_MOYENS,
    CRENEAUX_OCCUPES,
    DISPONIBILITE_MEDECINS,

    // Performance Cabinet
    TAUX_REMPLISSAGE,
    SATISFACTION_PATIENTS,
    ACTIVITE_PAR_PERIODE,
    PERFORMANCE_MEDECINS,
    TEMPS_ATTENTE_MOYEN
}
