package ma.whitecare.entities.enums;

public enum TypeNotification {

    RAPPEL_RDV,
    CONFIRMATION_RDV,
    MODIFICATION_RDV,
    FACTURE_IMPAYEE,
    PAIEMENT_RECU,
    URGENCE_MEDICALE ,
    RAPPEL_CONTROLE,
    ORDONNANCE_EXPIREE,
    NOUVEAU_PATIENT,
    ANNIVERSAIRE_PATIENT,
    SAUVEGARDE_AUTO,
    ALERTE_SYSTEME,
    MAINTENANCE_PLANIFIEE
}