# Beans (Repositories) - Tous les beans dont le nom se termine par "Repo" sont automatiquement chargés
# Format: nomBean = nom.complet.ClasseImpl

# Module Patient
patientRepo = ma.whitecare.repository.modules.patient.impl.PatientRepositoryImpl
antecedentRepo = ma.whitecare.repository.modules.patient.impl.AntecedentRepositoryImpl

# Module Cabinet
cabinetRepo = ma.whitecare.repository.modules.cabinet.impl.CabinetMedicaleRepositoryImpl
chargesRepo = ma.whitecare.repository.modules.cabinet.impl.ChargesRepositoryImpl
revenuesRepo = ma.whitecare.repository.modules.cabinet.impl.RevenuesRepositoryImpl

# Module UserManager
medecinRepo = ma.whitecare.repository.modules.UserManager.impl.MedecinRepositoryImpl
roleRepo = ma.whitecare.repository.modules.UserManager.impl.RoleRepositoryImpl
secretaireRepo = ma.whitecare.repository.modules.UserManager.impl.SecretaireRepositoryImpl
staffRepo = ma.whitecare.repository.modules.UserManager.impl.StaffRepositoryImpl
utilisateurRepo = ma.whitecare.repository.modules.UserManager.impl.UtilisateurRepositoryImpl

# Module DossierMedical
dossierRepo = ma.whitecare.repository.modules.dossierMedical.impl.DossierMedicalRepositoryImpl
consultationRepo = ma.whitecare.repository.modules.dossierMedical.impl.ConsultationRepositoryImpl
interventionRepo = ma.whitecare.repository.modules.dossierMedical.impl.InterventionRepositoryImpl
prescriptionRepo = ma.whitecare.repository.modules.dossierMedical.impl.PrescriptionRepositoryImpl
situationFinanciereRepo = ma.whitecare.repository.modules.dossierMedical.impl.SituationFinanciereRepositoryImpl

# Module Facture
factureRepo = ma.whitecare.repository.modules.facture.FactureRepositoryImpl

# Module Medicament
medicamentRepo = ma.whitecare.repository.modules.Medicament.MedicamentRepositoryImpl

# Module Actes
acteRepo = ma.whitecare.repository.modules.actes.impl.ActeRepositoryImpl

# Module Agenda
agendaRepo = ma.whitecare.repository.modules.agenda.impl.AgendaRepositoryImpl

# Module Certificat
certificatRepo = ma.whitecare.repository.modules.certificat.impl.CertificatRepositoryImpl

# Module Ordonnance
ordonnanceRepo = ma.whitecare.repository.modules.Ordonnance.OrdonnanceRepositoryImpl

# Module RDV
rdvRepo = ma.whitecare.repository.modules.rdv.impl.RDVRepositoryImpl

# Module Auth
authentificationRepo = ma.whitecare.repository.modules.auth.AuthenticationRepositoryImpl

# Module Statistiques
statistiqueRepo = ma.whitecare.repository.modules.statistiques.impl.StatistiqueRepositoryImpl

